dynamixels:
  port_info:
    port_name: /dev/ttyACM0
    baudrate: 2000000
    protocol_version: 2
  control_mode: position
  device_info:
    No1:
      id: 1
      model_number: 321
    No2:
      id: 2
      model_number: 311
    No3:
      id: 3
      model_number: 311
    No4:
      id: 4
      model_number: 311
    No5:
      id: 5
      model_number: 311
    No6:
      id: 6
      model_number: 311
    No7:
      id: 7
      model_number: 311
    No8:
      id: 8
      model_number: 311
    No9:
      id: 9
      model_number: 311
    No10:
      id: 10
      model_number: 311
    No11:
      id: 11
      model_number: 311
    No12:
      id: 12
      model_number: 311
    No13:
      id: 13
      model_number: 311
    No14:
      id: 14
      model_number: 311
    No15:
      id: 15
      model_number: 311
    No16:
      id: 16
      model_number: 311
    No17:
      id: 17
      model_number: 311
    No18:
      id: 18
      model_number: 311
    No19:
      id: 19
      model_number: 311



  read_values:
    read_position: true
    read_velocity: true
    read_effort: true
IMU:
  name: IMU
  frame: IMU_frame
  read: true
      
  